# -*- coding: utf-8 -*-
# SPDX-FileCopyrightText: : 2017-2023 The PyPSA-Eur Authors
#
# SPDX-License-Identifier: MIT
HighDemand:
  weather_year: 2012
  electricity:
    transmission_limit: v1
  solving:
    options:
      noisy_costs: false
    constraints:
      decentral_heat_pump_budgets:
        DE: # UBA MWMS, Projektionsbericht 2025, Abbildung 48
          2025: 12.0
      limits_capacity_min:
        Generator:
          onwind:
            DE:
              2030: 115   # Wind-an-Land Law
              2035: 157   # Wind-an-Land Law
          offwind:
            DE:
              2035: 40   # 40 Wind-auf-See Law
          solar:
            DE: # EEG2023; Ziel for 2024: 88 GW and for 2026: 128 GW,        
              2025: 101   # assuming at least 1/3 of buildout reached in 2025
              2030: 215   # PV strategy
              2035: 309
      limits_capacity_max:
        Generator:
          onwind:
            DE:
              2030: 115 # EEG2023 Ziel für 2030 + 5 GW
          solar:
            DE:
              2030: 215 # PV Ziel 2030
              2035: 309
  first_technology_occurrence:
    Link:
      urban central water pits charger: 2040 # essentially moving pits out of the optimization horizon to forbid them
      urban central water pits discharger: 2040
    Store:
      urban central water pits: 2040

HighDemandNoFlex:
  weather_year: 2012
  electricity:
    transmission_limit: v1
  iiasa_database:
    no_flex_lt_run: true
  solving:
    options:
      noisy_costs: false
    constraints:
      decentral_heat_pump_budgets:
        DE: # UBA MWMS, Projektionsbericht 2025, Abbildung 48
          2025: 12.0
      limits_capacity_min:
        Generator:
          onwind:
            DE:
              2030: 115   # Wind-an-Land Law
              2035: 157   # Wind-an-Land Law
          offwind:
            DE:
              2035: 40   # 40 Wind-auf-See Law
          solar:
            DE: # EEG2023; Ziel for 2024: 88 GW and for 2026: 128 GW,        
              2025: 101   # assuming at least 1/3 of buildout reached in 2025
              2030: 215   # PV strategy
              2035: 309
      limits_capacity_max:
        Generator:
          onwind:
            DE:
              2030: 115 # EEG2023 Ziel für 2030 + 5 GW
          solar:
            DE:
              2030: 215 # PV Ziel 2030
              2035: 309
  first_technology_occurrence:
    Link:
      urban central water pits charger: 2040 # essentially moving pits out of the optimization horizon to forbid them
      urban central water pits discharger: 2040
    Store:
      urban central water pits: 2040

LowDemand: # Demand and capacities from UBA
  weather_year: 2012
  electricity:
    transmission_limit: v1
  iiasa_database:
    uba_for_industry:
    - 2025
    - 2030
    - 2035
    uba_for_mobility:
    - 2025
    - 2030
    - 2035
    uba_for_rescom_electricity:
    - 2030
  offshore_nep_force:
    delay_years: 2
  solving:
    options:
      noisy_costs: false
    constraints:
      decentral_heat_pump_budgets:
        DE: # UBA MWMS, Projektionsbericht 2025, Abbildung 48
          2025: 12.0
          2030: 26.0
          2035: 38.0
      # central_heat_pump_budgets:
      #   DE: # UBA MWMS, Projektionsbericht 2025, Abbildung 22
      #     2025: 7.0
      #     2030: 26.0
      #     2035: 52.0
      # Capacities from UBA are here: https://datacube.uba.de/vis?lc=de&df[ds]=dc-release&df[id]=DF_CROSS_PROJECTION_REPORT_CORE_INDICATORS_25&df[ag]=UBA&df[vs]=1.0&av=true&dq=..INSTALLIERTE_LEISTUNG_GROSSBATTERIESPEICHER%2BINSTALLIERTE_LEISTUNG_WIND_AN_LAND%2BINSTALLIERTE_LEISTUNG_WIND_AUF_SEE%2BINSTALLIERTE_LEISTUNG_PV...&pd=2025%2C&to[TIME_PERIOD]=false&pg=0&vw=tb
      limits_capacity_min:
        Generator:
          onwind:
            DE:
              2030: 103.99
              2035: 145.41
          offwind:
            DE:
              2030: 26.77
              2035: 39.97
          solar:
            DE:
              2030: 214.55
              2035: 308.60
        Link:
          H2 electrolysis:
            DE:
              2030: 0
      limits_capacity_max:
        Generator:
          onwind:
            DE:
              2030: 103.99
              2035: 145.41
          offwind:
            DE:
              2030: 26.77
              2035: 39.97
          solar:
            DE:
              2030: 214.55
              2035: 308.60
  first_technology_occurrence:
    Link:
      urban central water pits charger: 2040 # essentially moving pits out of the optimization horizon to forbid them
      urban central water pits discharger: 2040
    Store:
      urban central water pits: 2040

LowDemandNoFlex:
  weather_year: 2012
  electricity:
    transmission_limit: v1
  iiasa_database:
    no_flex_lt_run: true
    uba_for_industry:
    - 2025
    - 2030
    - 2035
    uba_for_mobility:
    - 2025
    - 2030
    - 2035
    uba_for_rescom_electricity:
    - 2030
  offshore_nep_force:
    delay_years: 2
  solving:
    options:
      noisy_costs: false
    constraints:
      decentral_heat_pump_budgets:
        DE: # UBA MWMS, Projektionsbericht 2025, Abbildung 48
          2025: 12.0
          2030: 26.0
          2035: 38.0
      limits_capacity_min:
        Generator:
          onwind:
            DE:
              2030: 103.99
              2035: 145.41
          offwind:
            DE:
              2030: 26.77
              2035: 39.97
          solar:
            DE:
              2030: 214.55
              2035: 308.60
        Link:
          H2 electrolysis:
            DE:
              2030: 0
      limits_capacity_max:
        Generator:
          onwind:
            DE:
              2030: 103.99
              2035: 145.41
          offwind:
            DE:
              2030: 26.77
              2035: 39.97
          solar:
            DE:
              2030: 214.55
              2035: 308.60
  first_technology_occurrence:
    Link:
      urban central water pits charger: 2040 # essentially moving pits out of the optimization horizon to forbid them
      urban central water pits discharger: 2040
    Store:
      urban central water pits: 2040

LowRES: # Demand from UBA, lower RES capacities
  electricity:
    transmission_limit: v1
  iiasa_database:
    uba_for_industry:
    - 2025
    - 2030
    - 2035
    uba_for_mobility:
    - 2025
    - 2030
    - 2035
    uba_for_rescom_electricity:
    - 2030
  offshore_nep_force:
    delay_years: 2
  solving:
    options:
      noisy_costs: false
    constraints:
      decentral_heat_pump_budgets:
        DE: # UBA MWMS, Projektionsbericht 2025, Abbildung 48
          2025: 12.0
          2030: 26.0
          2035: 38.0
      # central_heat_pump_budgets:
      #   DE: # UBA MWMS, Projektionsbericht 2025, Abbildung 22
      #     2025: 7.0
      #     2030: 26.0
      #     2035: 52.0
      limits_capacity_min:
        Generator:
          onwind:
            DE:
              2030: 0
              2035: 0
          offwind:
            DE:
              2030: 0
              2035: 0
        Link:
          H2 electrolysis:
            DE:
              2030: 0
      limits_capacity_max:
        Generator:
          onwind:
            DE:
              2030: 100
          offwind:
            DE:
              2030: 21
          solar:
            DE:
              2030: 180
  first_technology_occurrence:
    Link:
      urban central water pits charger: 2040 # essentially moving pits out of the optimization horizon to forbid them
      urban central water pits discharger: 2040
    Store:
      urban central water pits: 2040


LowRESNoFlex:
  electricity:
    transmission_limit: v1
  iiasa_database:
    no_flex_lt_run: true
    uba_for_industry:
    - 2025
    - 2030
    - 2035
    uba_for_mobility:
    - 2025
    - 2030
    - 2035
    uba_for_rescom_electricity:
    - 2030
  offshore_nep_force:
    delay_years: 2
  solving:
    options:
      noisy_costs: false
    constraints:
      decentral_heat_pump_budgets:
        DE: # UBA MWMS, Projektionsbericht 2025, Abbildung 48
          2025: 12.0
          2030: 26.0
          2035: 38.0
      # central_heat_pump_budgets:
      #   DE: # UBA MWMS, Projektionsbericht 2025, Abbildung 22
      #     2025: 7.0
      #     2030: 26.0
      #     2035: 52.0
      limits_capacity_min:
        Generator:
          onwind:
            DE:
              2030: 0
              2035: 0
          offwind:
            DE:
              2030: 0
              2035: 0
        Link:
          H2 electrolysis:
            DE:
              2030: 0
      limits_capacity_max:
        Generator:
          onwind:
            DE:
              2030: 100
          offwind:
            DE:
              2030: 21
          solar:
            DE:
              2030: 180
  first_technology_occurrence:
    Link:
      urban central water pits charger: 2040 # essentially moving pits out of the optimization horizon to forbid them
      urban central water pits discharger: 2040
    Store:
      urban central water pits: 2040

ExPol:
# UBA CO2 pathway instead of KSG targets
# European CO2 pathway fixed at 2030 for 2035-2050
# Kernnetz is not assumed to be built
# Not forcing renewables after 2030

  iiasa_database:
    reference_scenario: ExPol

  co2_budget_DE_source: UBA

  co2_budget:
    2020: 0.720 # average emissions of 2019 to 2021 relative to 1990, excl LULUCF, EEA data, European Environment Agency. (2023a). Annual European Union greenhouse gas inventory 1990–2021 and inventory report 2023 - CRF Table. https://unfccc.int/documents/627830
    2025: 0.675 # With existing measures (WEM) projection, CO2 excl LULUCF, European Environment Agency. (2023e). Member States’ greenhouse gas (GHG) emission projections 2023. https://www.eea.europa.eu/en/datahub/datahubitem-view/4b8d94a4-aed7-4e67-a54c-0623a50f48e8
    2030: 0.569
    2035: 0.502
    2040: 0.452
    2045: 0.431
    2050: 0.419

  costs:
    transmission: "underground" # either overhead line ("overhead") or underground cable ("underground")
  solving:
    constraints:
      limits_capacity_min:
        Generator:
          onwind:
            DE:
              2030: 86.5   # 75 % Wind-an-Land Law
          offwind:
            DE:
              2030: 17.3
              2035: 29.3
          solar:
            DE:
              2030: 161.25   # 75 % PV strategy
      # boundary condition of maximum volumes
      limits_capacity_max:
        Generator:
          offwind:
            DE:
              2020: 7.8
              2025: 11.3
              2030: 17.3 # 12 less than NEP, because of 1 year delay
              2035: 40 # 29.3 + half of extra projects
          onwind:
            DE:
              2030: 94.5 # uba Projektionsbericht
          solar:
            DE:
              2030: 215 # uba Projektionsbericht


  sector:
    district_heating:
      potential: 0.1

  offshore_nep_force:
    cutin_year: 2025
    cutout_year: 2035 # Hackily reduced to 2030 if delay_years: 1
    delay_years: 1


KN2045_Mix:
# Default scenario, defined in pypsa.de.yaml
# Ausgewogener Mix an Technologien zur Dekarbonisierung der Sektoren
# Breites Energieträgerportfolio in der Endenergie (Strom, Wasserstoff, synthetische Kraftstoffe)
# Ausbau der erneuerbare Stromerzeugung erreicht politisch gesetzte Ziele
# Importe erneuerbar erzeugter Energien auf mittlerem Niveau
# dient als Referenzszenario in der Familie der Ariadne-Szenarien


KN2045_Elek:
# Fokus auf dem Hochlauf von Technologien zur direkten Elektrifizierung der Sektoren
# Strom als präferierter Energieträger in der Endenergie, andere Energieträger ergänzend, wo nötig (Wasserstoff, synthetische Kraftstoffe)
# Ausbau der erneuerbaren Stromerzeugung erreicht politisch gesetzte Ziele
# Importe erneuerbar erzeugter Energien auf mittlerem Niveau

  iiasa_database:
    reference_scenario: KN2045_Elek

  solving:
    constraints:
      limits_volume_max:
        # constrain electricity import in TWh
        electricity_import:
          DE:
            2020: -20
            2025: 0
            2030: 0
            2035: 50
            2040: 100
            2045: 150
            2050: 150
        electrolysis:
          DE:
            2020: 0
            2025: 5
            2030: 45
            2035: 95
            2040: 145
            2045: 200
            2050: 200
        h2_derivate_import:
          DE:
            2020: 0
            2025: 0
            2030: 10
            2035: 70
            2040: 130
            2045: 200
            2050: 200
        h2_import:
          DE:
            2020: 0
            2025: 5
            2030: 10
            2035: 90
            2040: 170
            2045: 250
            2050: 250

  industry:
    steam_biomass_fraction: 0.4
    steam_hydrogen_fraction: 0.1
    steam_electricity_fraction: 0.5

KN2045_H2:
# Fokus stärker auf dem Hochlauf von Technologien zur indirekten Elektrifizierung der Sektoren
# Verstärkter Einsatz von Wasserstoff und synthetischen Kraftstoffen - erneuerbar erzeugt und auch importiert
# Direkte Elektrifizierung spielt dennoch wesentliche Rolle bei der Dekarbonisierung der Endenergie
# Ausbau der erneuerbaren Stromerzeugung erreicht politisch gesetzte Ziele

  iiasa_database:
    reference_scenario: KN2045_H2

  solving:
    constraints:
      limits_volume_max:
        # constrain electricity import in TWh
        electricity_import:
          DE:
            2020: -20
            2025: 0
            2030: 0
            2035: 30
            2040: 70
            2045: 100 # scenario guidelines
            2050: 100

        # constrain hydrogen import in TWh
        h2_import:
          DE:
            2020: 0
            2025: 5
            2030: 45 # scenario guidelines
            2035: 155
            2040: 265
            2045: 400 # scenario guidelines
            2050: 400
        # import of h2 derivatives in TWh
        h2_derivate_import:
          DE:
            2020: 0
            2025: 0
            2030: 10 # scenario guidelines
            2035: 140
            2040: 270
            2045: 400 # scenario guidelines
            2050: 400
        electrolysis:
          DE:
            2020: 0
            2025: 5
            2030: 45 # scenario guidelines
            2035: 160
            2040: 275
            2045: 400 # scenario guidelines
            2050: 400

      limits_volume_min:
        electrolysis:
          DE:
            2025: 0
            2030: 0
            2035: 0
            2040: 0
            2045: 200
            2050: 200

  industry:
    steam_biomass_fraction: 0.4
    steam_hydrogen_fraction: 0.5
    steam_electricity_fraction: 0.1

KN2045_NFniedrig:
# Ausgewogener Mix an Technologien zur Dekarbonisierung der Sektoren
# Breites Energieträgerportfolio in der Endenergie (Strom, Wasserstoff, synthetische Kraftstoffe)
# Ausbau der erneuerbare Stromerzeugung erreicht politisch gesetzte Ziele
# Importe erneuerbar erzeugter Energien auf mittlerem Niveau
# dient als Referenzszenario in der Familie der Ariadne-Szenarien

  iiasa_database:
    reference_scenario: KN2045_NFniedrig

  sector:
    reduce_space_heat_exogenously_factor:
      2020: 0.0
      2025: 0.08
      2030: 0.16
      2035: 0.25
      2040: 0.34
      2045: 0.43
      2050: 0.50

KN2045_NFhoch:
# Ausgewogener Mix an Technologien zur Dekarbonisierung der Sektoren
# Breites Energieträgerportfolio in der Endenergie (Strom, Wasserstoff, synthetische Kraftstoffe)
# Ausbau der erneuerbare Stromerzeugung erreicht politisch gesetzte Ziele
# Importe erneuerbar erzeugter Energien auf mittlerem Niveau
# dient als Referenzszenario in der Familie der Ariadne-Szenarien

  iiasa_database:
    reference_scenario: KN2045_NFhoch

  sector:
    reduce_space_heat_exogenously_factor:
      2020: 0.0
      2025: 0.06
      2030: 0.12
      2035: 0.18
      2040: 0.24
      2045: 0.29
      2050: 0.33
